"""
generate_profiles.py
Generates LLM text profiles for all users (long-term user preferences only), 
then SBERT-encodes them and saves both the raw text and embeddings.

Context-rec design: Only the long-term profile is needed. The user's long-term
preferences serve as the stable base representation, enriched with situation-specific
contexts at inference time (generated by generate_contexts.py).

Pipeline:
  - For each user, assemble their interaction history as JSON (last 15 items max)
    {title, description, timestamp} using the recovered item metadata
  - Call the selected LLM with prompt_long to generate long-term user description
  - SBERT-encode the long-term profile text
  - Save two outputs:
      bert_long_term_user_profiles_{MODEL}_text.pkl  ← raw text, needed by generate_contexts.py
      bert_long_term_user_profiles_{MODEL}.pkl       ← 384-dim embeddings, used by context_rec.py

Design notes:
  - Only ONE profile type generated (long-term). Short/general are unused in context-rec.
  - User history limited to last 15 interactions to stay under context window
  - Descriptions truncated to 300 chars to reduce token count
  - Warnings about token length suppressed

Usage
-----
python preprocessing/generate_profiles.py --split all
python preprocessing/generate_profiles.py --llm_model microsoft/phi-3-mini-4k-instruct --max_users 50
python preprocessing/generate_profiles.py --llm_model mistralai/Mistral-7B-Instruct-v0.1

The model is downloaded from Hugging Face on first run and cached locally.
For gated models (e.g. Llama) set HF_TOKEN in your environment first.

Recommended models:
  - microsoft/phi-3-mini-4k-instruct (3.8B) — default, fastest
  - mistralai/Mistral-7B-Instruct-v0.1 (7B) — balanced quality/speed
  - meta-llama/Llama-2-7b-chat (7B) — good quality, needs HF_TOKEN

Outputs (data/movies/)
------------------------------------------------------
bert_long_term_user_profiles_{MODEL}_text.pkl
bert_long_term_user_profiles_{MODEL}.pkl
"""

import json
import pickle
import argparse
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from transformers import pipeline as hf_pipeline
from sentence_transformers import SentenceTransformer

# Suppress verbose warnings from transformers library
warnings.filterwarnings("ignore", message=".*max_new_tokens.*max_length.*")
warnings.filterwarnings("ignore", message=".*Token indices sequence length.*")
warnings.filterwarnings("ignore", message=".*torch_dtype.*deprecated.*")
warnings.filterwarnings("ignore", message=".*temperature.*not valid.*")


# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------
DATASET             = "movies"
DEFAULT_LLM_MODEL  = "microsoft/phi-3-mini-4k-instruct"
SBERT_MODEL         = "all-MiniLM-L6-v2"

# Default generation parameters (can be overridden via CLI)
DEFAULT_TEMPERATURE = 0.1    # Fast/deterministic (old: 0.2)
DEFAULT_MAX_TOKENS  = 150    # Fast (old: 256)
DEFAULT_SAMPLING    = False  # Greedy decoding, faster (old: True)
MAX_HISTORY_ITEMS   = 15     # Only include most recent N items

DATA_DIR      = Path(__file__).resolve().parents[1] / "data" / DATASET
PROMPT_DIR    = Path(__file__).resolve().parents[1] / "prompt"

PROFILE_TYPES = {
    "long":    PROMPT_DIR / "prompt_long.txt",
}

OUT_NAME = {
    "long":    "bert_long_term_user_profiles",
}


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)


def save_pickle(obj, path):
    with open(path, "wb") as f:
        pickle.dump(obj, f)


def load_prompt(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def build_history_json(user_id: int, interaction_rows, item_meta: dict) -> str:
    """
    Construct a JSON list of {title, description, timestamp} for a user's history.
    - Only includes most recent MAX_HISTORY_ITEMS interactions to stay under context window
    - Descriptions truncated to 300 chars to reduce token count
    - Rows sorted chronologically (ascending timestamp)
    """
    items = []
    for row in sorted(interaction_rows, key=lambda r: r["timestamp"])[-MAX_HISTORY_ITEMS:]:
        iid = int(row["item_id"])
        meta = item_meta.get(iid)
        if meta is None:
            continue
        # Truncate description to keep token count reasonable
        desc = meta["description_text"][:300]
        if len(meta["description_text"]) > 300:
            desc += "..."
        items.append({
            "title":       meta["title"],
            "description": desc,
            "timestamp":   int(row["timestamp"]),
        })
    return json.dumps(items, ensure_ascii=False)


def build_llm_pipeline(model_name: str):
    """Load a HuggingFace text-generation pipeline."""
    print(f"Loading LLM: {model_name} (downloading on first run) ...")
    
    # Check if this is a 7B+ model (slower) and recommend smaller alternative
    if "7b" in model_name.lower() or "13b" in model_name.lower():
        print(f"  ⚠️  Warning: {model_name} is a large model (slow inference)")
        print(f"      For faster generation, use: microsoft/phi-3-mini-4k-instruct (3.8B)")
    
    dtype = torch.float16 if torch.cuda.is_available() else torch.float32
    
    # Keep it simple to avoid cache issues
    pipe = hf_pipeline(
        "text-generation",
        model=model_name,
        device_map="auto",
        torch_dtype=dtype,
    )
    
    print(f"  LLM loaded on: {pipe.device}")
    return pipe


def llm_call(pipe, prompt_text: str, max_tokens: int, temperature: float, do_sample: bool) -> str:
    """Run inference via pipeline and extract only the generated (new) text using marker-based extraction."""
    # Unique marker to cleanly separate prompt from generation
    MARKER = "\n[END_OF_PROMPT]\n"
    
    try:
        # Call pipeline with marker so we can reliably find where prompt ends
        full_prompt = prompt_text + MARKER
        
        output = pipe(
            full_prompt,
            max_new_tokens=max_tokens,
            do_sample=do_sample,
            temperature=temperature if do_sample else 1.0,
        )
        
        result = output[0]["generated_text"]
        
        # Find where the marker is and extract everything after it
        if MARKER in result:
            marker_pos = result.rfind(MARKER)  # Find the last occurrence
            generated_only = result[marker_pos + len(MARKER):].strip()
            
            if generated_only and len(generated_only) > 20:
                return generated_only
        
        # Fallback: if extraction failed, return empty string (will be skipped)
        return ""
        
    except Exception as e:
        print(f"\n  ⚠️  Generation error: {str(e)[:100]}")
        return ""


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
def main(args):
    llm_model = args.llm_model
    max_tokens = args.max_tokens
    temperature = args.temperature
    do_sample = args.sampling
    
    # Extract model name for file naming
    model_name_short = llm_model.split("/")[-1] if "/" in llm_model else llm_model
    print(f"Using model: {llm_model}")
    print(f"Output files will include: {model_name_short}")
    print(f"Generation config: max_tokens={max_tokens}, temperature={temperature:.2f}, do_sample={do_sample}")
    
    # --- Load interactions ---
    splits_to_use = (
        ["train", "validation", "test"] if args.split == "all" else [args.split]
    )
    dfs = []
    for s in splits_to_use:
        df = pd.read_csv(DATA_DIR / f"{s}.csv")
        dfs.append(df)
    interactions = pd.concat(dfs, ignore_index=True)

    # --- Load item metadata (produced by rebuild_metadata.py) ---
    meta_path = DATA_DIR / "item_metadata.pkl"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"{meta_path} not found. Run preprocessing/rebuild_metadata.py first."
        )
    item_meta_df = load_pickle(str(meta_path))
    item_meta = {
        int(row["item_id"]): {
            "title":            row["title"],
            "description_text": row["description_text"],
        }
        for _, row in item_meta_df.iterrows()
    }
    print(f"Loaded metadata for {len(item_meta)} items.")

    # Group interactions by user
    user_interactions = {}
    for row in interactions.itertuples(index=False):
        uid = int(row.user_id)
        user_interactions.setdefault(uid, []).append(
            {"item_id": int(row.item_id), "timestamp": int(row.timestamp)}
        )
    user_ids = sorted(user_interactions.keys())
    if args.max_users is not None:
        user_ids = user_ids[:args.max_users]
        print(f"Users to process: {len(user_ids)} (capped by --max_users)")
    else:
        print(f"Users to process: {len(user_ids)}")

    # --- Load prompts ---
    prompts = {k: load_prompt(v) for k, v in PROFILE_TYPES.items()}

    # --- Set up LLM pipeline ---
    pipe = build_llm_pipeline(args.llm_model)

    # --- SBERT ---
    print(f"Loading SBERT: {SBERT_MODEL}")
    sbert = SentenceTransformer(SBERT_MODEL)

    # --- Generate profiles ---
    # Storage: profile_type -> {user_id: {"text": str, "emb": np.ndarray}}
    results = {k: {} for k in PROFILE_TYPES}

    print(f"\nGenerating long-term user profiles for {len(user_ids)} users...")
    pbar = tqdm(total=len(user_ids), desc="Profile generation", unit="users")
    
    for idx, uid in enumerate(user_ids):
        history_json = build_history_json(uid, user_interactions[uid], item_meta)

        if not json.loads(history_json):
            # User has no items with recovered metadata — skip
            pbar.update(1)
            continue

        # Generate only long-term profile
        # Note: llm_call() internally adds a marker to separate prompt from generation
        full_prompt = prompts["long"] + "\n\nUser interactions:\n" + history_json
        profile_text = llm_call(pipe, full_prompt, max_tokens, temperature, do_sample)
        
        # Skip if generation failed
        if not profile_text or len(profile_text.strip()) < 20:
            pbar.update(1)
            continue
        
        results["long"][uid] = {"text": profile_text}
        pbar.update(1)
    
    pbar.close()
    num_generated = len(results["long"])
    print(f"\nGenerated long-term profiles for {num_generated} users")
    
    if num_generated == 0:
        print("❌ ERROR: No profiles were generated. Check the LLM output above.")
        exit(1)

    # --- SBERT-encode ---
    print(f"\nSBERT-encoding {num_generated} long-term profiles...")
    uid_list = sorted(results["long"].keys())
    texts = [results["long"][u]["text"] for u in uid_list]

    embs = sbert.encode(
        texts,
        batch_size=256,
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=True,
    ).astype(np.float32)

    # --- Save text pkl (needed by generate_contexts.py) ---
    text_df = pd.DataFrame({
        "user_id":      uid_list,
        "profile_text": texts,
    })
    # Include num_users and temperature in filename for tracking
    temp_str = f"{temperature:.2f}".replace(".", "")  # e.g., 0.15 -> 015
    text_path = DATA_DIR / f"{OUT_NAME['long']}_{model_name_short}_N{num_generated}_T{temp_str}_text.pkl"
    save_pickle(text_df, str(text_path))
    print(f"  ✓ Saved text profiles → {text_path.name}")

    # --- Save embedding pkl (used by context_rec.py) ---
    emb_df = pd.DataFrame({
        "user_id": uid_list,
        "profile": list(embs),
    })
    emb_path = DATA_DIR / f"{OUT_NAME['long']}_{model_name_short}_N{num_generated}_T{temp_str}.pkl"
    save_pickle(emb_df, str(emb_path))
    print(f"  ✓ Saved embedding profiles → {emb_path.name}")

    print("\n✓ Done. Long-term profiles generated and encoded.")


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Generate LLM user profiles for the movies dataset."
    )
    parser.add_argument(
        "--split",
        type=str,
        default="all",
        choices=["train", "validation", "test", "all"],
        help="Which interaction split(s) to include in user histories.",
    )
    parser.add_argument(
        "--llm_model",
        type=str,
        default=DEFAULT_LLM_MODEL,
        help="HuggingFace model ID, e.g. 'microsoft/phi-3-mini-4k-instruct'.",
    )
    parser.add_argument(
        "--max_users",
        type=int,
        default=None,
        help="Cap the number of users processed (useful for smoke-tests).",
    )
    parser.add_argument(
        "--max_tokens",
        type=int,
        default=DEFAULT_MAX_TOKENS,
        help=f"Max tokens to generate per profile (default: {DEFAULT_MAX_TOKENS}, old: 256).",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=DEFAULT_TEMPERATURE,
        help=f"Temperature for generation (default: {DEFAULT_TEMPERATURE}, old: 0.2, higher=more random).",
    )
    parser.add_argument(
        "--sampling",
        action="store_true",
        help="Use sampling instead of greedy decoding (slower but more diverse, old behavior).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_arguments()
    main(args)
