"""
generate_contexts.py

For each (user, GT_item) pair in the test set, generate K mood/situation contexts
using an LLM, then SBERT-encode them and save both:
  1) raw context texts
  2) context embeddings

Outputs:
    data/<dataset>/bert_context_profiles_test.pkl
        {(user_id, item_id): List[np.ndarray of shape (384,)]}

    data/<dataset>/bert_context_profiles_test_text.pkl
        {(user_id, item_id): List[str]}

Required inputs
---------------
1. bert_long_term_user_profiles_{MODEL}_text.pkl
       DataFrame with columns: user_id (int), profile_text (str)
       Raw LLM-generated long-term profile text (not SBERT-encoded).
       Generated by preprocessing/generate_profiles.py with matching --llm_model.

2. item_metadata.pkl
       DataFrame with columns: item_id (int), title (str), description_text (str)
       Raw item titles and descriptions used for context prompting.
       Generated by preprocessing/rebuild_metadata.py.

3. data/<dataset>/test.csv
       Interaction file with columns: user_id, item_id (leave-one-out GT items).

4. prompt/prompt_context.txt
       Template with placeholders {user_description}, {target_title}, {target_description}.

Usage
-----
python code/generate_contexts.py --dataset movies --num_contexts 3
python code/generate_contexts.py --llm_model microsoft/phi-3-mini-4k-instruct --num_contexts 3
python code/generate_contexts.py --llm_model microsoft/phi-3-mini-4k-instruct --num_contexts 1 --max_pairs 100
python code/generate_contexts.py --llm_model microsoft/phi-3-mini-4k-instruct --num_contexts 3 --profile_file bert_long_term_user_profiles_phi-3-mini-4k-instruct_N5000_T015_text.pkl

Notes
-----
- `num_contexts` = number of separate context candidates generated per (user, item) pair.
- This version saves raw generated texts so you can inspect adequacy later.
- It uses one LLM call per pair with `num_return_sequences=num_contexts`, which is much faster
  than making `num_contexts` separate calls.
"""

import argparse
import pickle
import warnings
from pathlib import Path

import pandas as pd
import torch
from tqdm import tqdm
from transformers import pipeline as hf_pipeline
from sentence_transformers import SentenceTransformer


# -------------------
# Warning suppression
# -------------------
warnings.filterwarnings("ignore", message=".*torch_dtype.*deprecated.*")
warnings.filterwarnings("ignore", message=".*generation_config.*deprecated.*")
warnings.filterwarnings("ignore", message=".*max_new_tokens.*max_length.*")
warnings.filterwarnings("ignore", message=".*Token indices sequence length.*")
warnings.filterwarnings("ignore", message=".*temperature.*not valid.*")


# -------------------
# Defaults / config
# -------------------
DEFAULT_DATASET = "movies"
DEFAULT_NUM_CONTEXTS = 5
DEFAULT_SBERT_MODEL = "all-MiniLM-L6-v2"
DEFAULT_LLM_MODEL = "microsoft/phi-3-mini-4k-instruct"

CONTEXT_TEMPERATURE = 0.9
CONTEXT_MAX_NEW_TOKENS = 96   # 200 was usually overkill for a 200–400 char context
SBERT_BATCH_SIZE = 256

PROMPT_PATH = Path(__file__).resolve().parents[1] / "prompt" / "prompt_context.txt"


# -------------------
# Helpers
# -------------------
def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)


def save_pickle(obj, path, label=None):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(obj, f)
    if label:
        print(f"Saved {label} to {path}")
    else:
        print(f"Saved pickle to {path}")


def load_prompt_template(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def build_prompt(template, user_description, target_title, target_description):
    return (
        template
        .replace("{user_description}", user_description)
        .replace("{target_title}", target_title)
        .replace("{target_description}", target_description)
    )


def resolve_profile_file(data_dir: Path, llm_model: str, explicit_profile_file: str | None) -> Path:
    """
    Resolve the raw text profile file to use.

    Preference order:
      1) explicit --profile_file
      2) newest matching *_N*_T*_text.pkl
      3) fallback old-style *_text.pkl
    """
    if explicit_profile_file:
        profile_path = Path(explicit_profile_file)
        if not profile_path.is_absolute() and "/" not in str(profile_path) and "\\" not in str(profile_path):
            profile_path = data_dir / profile_path
        if not profile_path.exists():
            raise FileNotFoundError(
                f"Profile file not found: {profile_path}\n"
                f"Checked: {profile_path.resolve()}"
            )
        return profile_path

    model_name_short = llm_model.split("/")[-1] if "/" in llm_model else llm_model

    candidates = list(data_dir.glob(f"bert_long_term_user_profiles_{model_name_short}_N*_T*_text.pkl"))
    if candidates:
        # choose most recently modified, not lexicographically "largest"
        return max(candidates, key=lambda p: p.stat().st_mtime)

    fallback = data_dir / f"bert_long_term_user_profiles_{model_name_short}_text.pkl"
    if fallback.exists():
        return fallback

    raise FileNotFoundError(
        f"No raw text profile files found for model {llm_model} in {data_dir}\n"
        f"Tried:\n"
        f"  bert_long_term_user_profiles_{model_name_short}_N*_T*_text.pkl\n"
        f"  bert_long_term_user_profiles_{model_name_short}_text.pkl\n"
        f"Run: python preprocessing/generate_profiles.py --llm_model {llm_model}"
    )


# -------------------
# LLM pipeline setup
# -------------------
def build_llm_pipeline(model_name: str):
    print(f"Loading LLM: {model_name} (downloading on first run) ...")
    dtype = torch.float16 if torch.cuda.is_available() else torch.float32

    # Some transformers versions warn that torch_dtype is deprecated in pipeline().
    # dtype works in newer versions; if not supported, fall back to torch_dtype.
    try:
        pipe = hf_pipeline(
            "text-generation",
            model=model_name,
            device_map="auto",
            dtype=dtype,
        )
    except TypeError:
        pipe = hf_pipeline(
            "text-generation",
            model=model_name,
            device_map="auto",
            torch_dtype=dtype,
        )

    # Reduce noisy generation warnings if these fields exist
    try:
        if hasattr(pipe.model, "generation_config") and pipe.model.generation_config is not None:
            # avoid warning about both max_length and max_new_tokens being set
            pipe.model.generation_config.max_length = None
    except Exception:
        pass

    try:
        if pipe.tokenizer.pad_token_id is None and pipe.tokenizer.eos_token_id is not None:
            pipe.tokenizer.pad_token_id = pipe.tokenizer.eos_token_id
    except Exception:
        pass

    print(f"  LLM loaded on: {pipe.device}")
    return pipe


# -------------------
# LLM context generation
# -------------------
def extract_generated_texts(output):
    """
    Normalize HF pipeline outputs into a list[str].

    Expected cases:
      - output is list[dict]
      - each dict has generated_text
      - generated_text may be:
          * a list of chat messages
          * a plain string
    """
    texts = []

    if not isinstance(output, list):
        output = [output]

    for out in output:
        generated = out.get("generated_text", "")

        if isinstance(generated, list):
            # Chat-style output: take the last assistant message content
            if generated and isinstance(generated[-1], dict) and "content" in generated[-1]:
                text = generated[-1]["content"]
            else:
                text = str(generated)
        else:
            text = str(generated)

        text = text.strip()
        if text:
            texts.append(text)

    return texts


def generate_contexts_for_pair(pipe, prompt_text, num_contexts):
    """
    Generate `num_contexts` candidate contexts for one (user, item) pair
    in a single pipeline call.
    """
    messages = [{"role": "user", "content": prompt_text}]

    output = pipe(
        messages,
        max_new_tokens=CONTEXT_MAX_NEW_TOKENS,
        temperature=CONTEXT_TEMPERATURE,
        do_sample=True,
        num_return_sequences=num_contexts,
        pad_token_id=getattr(pipe.tokenizer, "pad_token_id", None),
    )

    texts = extract_generated_texts(output)

    # Deduplicate while preserving order
    seen = set()
    deduped = []
    for t in texts:
        if t not in seen:
            seen.add(t)
            deduped.append(t)

    return deduped


# -------------------
# Main
# -------------------
def main(args):
    dataset = args.dataset
    num_contexts = args.num_contexts
    llm_model = args.llm_model
    sbert_model_name = args.sbert_model

    data_dir = Path(__file__).resolve().parents[1] / "data" / dataset
    item_meta_path = data_dir / "item_metadata.pkl"
    test_path = data_dir / "test.csv"

    out_emb_path = data_dir / "bert_context_profiles_test.pkl"
    out_text_path = data_dir / "bert_context_profiles_test_text.pkl"

    user_text_path = resolve_profile_file(data_dir, llm_model, args.profile_file)

    print(f"Using LLM model: {llm_model}")
    if args.profile_file:
        print(f"Using specified profile file: {user_text_path.name}")
    else:
        print(f"Auto-detected profile file: {user_text_path.name}")

    print("Loading raw profile texts and item metadata...")
    user_text_df = load_pickle(str(user_text_path))
    item_meta_df = load_pickle(str(item_meta_path))
    test_df = pd.read_csv(str(test_path))

    # Build lookup dicts
    user_text = {
        int(row["user_id"]): row["profile_text"]
        for _, row in user_text_df.iterrows()
    }

    item_meta = {
        int(row["item_id"]): {
            "title": row["title"],
            "description_text": row["description_text"],
        }
        for _, row in item_meta_df.iterrows()
    }

    # Prompt template
    prompt_template = load_prompt_template(str(PROMPT_PATH))

    # LLM
    pipe = build_llm_pipeline(llm_model)

    # SBERT
    print(f"Loading SBERT model: {sbert_model_name}")
    sbert = SentenceTransformer(sbert_model_name)

    # Unique (user_id, item_id) test pairs
    raw_test_pairs = [
        (int(row.user_id), int(row.item_id))
        for row in test_df.itertuples(index=False)
    ]
    test_pairs = list(dict.fromkeys(raw_test_pairs))  # preserve order, drop duplicates

    if args.max_pairs is not None:
        test_pairs = test_pairs[:args.max_pairs]

    total = len(test_pairs)
    print(f"Generating {num_contexts} contexts for {total} test (user, item) pairs...")

    context_text_dict = {}   # {(user_id, item_id): [ctx_text1, ...]}
    context_emb_dict = {}    # {(user_id, item_id): [ctx_emb1, ...]}

    all_ctx_texts = []
    all_ctx_metadata = []

    missing_user_pairs = []
    missing_item_pairs = []
    empty_generation_pairs = []

    pbar = tqdm(total=total, desc="Generating contexts", unit="pairs")

    for user_id, item_id in test_pairs:
        if user_id not in user_text:
            missing_user_pairs.append((user_id, item_id))
            pbar.update(1)
            continue

        if item_id not in item_meta:
            missing_item_pairs.append((user_id, item_id))
            pbar.update(1)
            continue

        user_desc = str(user_text[user_id]).strip()
        item_title = str(item_meta[item_id]["title"]).strip()
        item_desc = str(item_meta[item_id]["description_text"]).strip()

        prompt_text = build_prompt(
            prompt_template,
            user_desc,
            item_title,
            item_desc,
        )

        ctx_texts = generate_contexts_for_pair(pipe, prompt_text, num_contexts)
        ctx_texts = [c.strip() for c in ctx_texts if c and c.strip()]

        if not ctx_texts:
            empty_generation_pairs.append((user_id, item_id))
            pbar.update(1)
            continue

        context_text_dict[(user_id, item_id)] = ctx_texts

        for ctx_idx, ctx_text in enumerate(ctx_texts):
            all_ctx_texts.append(ctx_text)
            all_ctx_metadata.append((user_id, item_id, ctx_idx))

        pbar.update(1)

    pbar.close()

    # Batch encode all generated contexts
    print(f"\nBatch-encoding {len(all_ctx_texts)} contexts with SBERT...")
    if all_ctx_texts:
        all_ctx_embs = sbert.encode(
            all_ctx_texts,
            batch_size=SBERT_BATCH_SIZE,
            convert_to_numpy=True,
            normalize_embeddings=True,
            show_progress_bar=True,
        )

        for (user_id, item_id, _ctx_idx), emb in zip(all_ctx_metadata, all_ctx_embs):
            if (user_id, item_id) not in context_emb_dict:
                context_emb_dict[(user_id, item_id)] = []
            context_emb_dict[(user_id, item_id)].append(emb)

    save_pickle(context_emb_dict, out_emb_path, label="context embeddings")
    save_pickle(context_text_dict, out_text_path, label="raw context texts")

    print("\nSummary")
    print("-------")
    print(f"Requested test pairs:         {total}")
    print(f"Pairs with saved contexts:    {len(context_emb_dict)}")
    print(f"Total generated contexts:     {len(all_ctx_texts)}")
    print(f"Missing user-profile pairs:   {len(missing_user_pairs)}")
    print(f"Missing item-metadata pairs:  {len(missing_item_pairs)}")
    print(f"Empty-generation pairs:       {len(empty_generation_pairs)}")

    if missing_user_pairs:
        print(f"First missing user-profile pairs: {missing_user_pairs[:5]}")
    if missing_item_pairs:
        print(f"First missing item-metadata pairs: {missing_item_pairs[:5]}")
    if empty_generation_pairs:
        print(f"First empty-generation pairs: {empty_generation_pairs[:5]}")

    print("\nDone.")


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Generate GT-aligned LLM contexts for test (user, item) pairs."
    )
    parser.add_argument("--dataset", type=str, default=DEFAULT_DATASET)
    parser.add_argument(
        "--num_contexts",
        type=int,
        default=DEFAULT_NUM_CONTEXTS,
        help="Number of context candidates to generate per (user, item) pair.",
    )
    parser.add_argument(
        "--llm_model",
        type=str,
        default=DEFAULT_LLM_MODEL,
        help="HuggingFace model ID, e.g. 'microsoft/phi-3-mini-4k-instruct'.",
    )
    parser.add_argument(
        "--sbert_model",
        type=str,
        default=DEFAULT_SBERT_MODEL,
        help="Sentence-Transformers model name for encoding contexts.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Seed placeholder (LLM generation remains stochastic unless you add stricter controls).",
    )
    parser.add_argument(
        "--profile_file",
        type=str,
        default=None,
        help="Path to raw text profile file (filename or full path). If omitted, auto-detects based on --llm_model.",
    )
    parser.add_argument(
        "--max_pairs",
        type=int,
        default=None,
        help="Limit to first N unique test pairs (useful for quick testing).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_arguments()
    main(args)