"""
generate_contexts.py
Preprocessing script: for each (user, GT_item) pair in the test set, generate K
mood/situation contexts using an LLM, then SBERT-encode them and save to disk.

The output is loaded by context_rec.py during context-augmented evaluation.

Output format:
    {(user_id, item_id): List[np.ndarray of shape (384,)]}
    saved as data/<dataset>/bert_context_profiles_test.pkl

Required inputs
---------------
1. bert_long_term_user_profiles_{MODEL}_text.pkl
       DataFrame with columns: user_id (int), profile_text (str)
       Raw LLM-generated long-term profile text (not SBERT-encoded).
       This is the same text that was encoded to produce bert_long_term_user_profiles_{MODEL}.pkl.
       Generated by preprocessing/generate_profiles.py with matching --llm_model.

2. item_metadata.pkl
       DataFrame with columns: item_id (int), title (str), description_text (str)
       Raw item titles and descriptions used for context prompting.
       Generated by preprocessing/rebuild_metadata.py.

3. data/<dataset>/test.csv
       Interaction file with columns: user_id, item_id (leave-one-out GT items).

4. prompt/prompt_context.txt
       Template with placeholders {user_description}, {target_title}, {target_description}.

Environment variables
---------------------
HF_TOKEN  — optional, required only for gated HuggingFace models (e.g. Llama).

Usage
-----
python code/generate_contexts.py --dataset movies --num_contexts 5
python code/generate_contexts.py --llm_model microsoft/phi-3-mini-4k-instruct --num_contexts 3
python code/generate_contexts.py --llm_model mistralai/Mistral-7B-Instruct-v0.1 --num_contexts 5

NOTE: --llm_model must match the model used in generate_profiles.py to find the profile files!
"""

import pickle
import argparse
import numpy as np
import pandas as pd
from pathlib import Path

import torch
from transformers import pipeline as hf_pipeline
from sentence_transformers import SentenceTransformer


# -------------------
# Configuration
# -------------------
DEFAULT_DATASET = "movies"
DEFAULT_NUM_CONTEXTS = 5
DEFAULT_SBERT_MODEL = "all-MiniLM-L6-v2"
DEFAULT_LLM_MODEL = "microsoft/phi-3-mini-4k-instruct"  # Match generate_profiles.py
CONTEXT_TEMPERATURE = 0.9   # high temperature for diverse contexts
CONTEXT_MAX_NEW_TOKENS = 200
PROMPT_PATH = Path(__file__).resolve().parents[1] / "prompt" / "prompt_context.txt"


# -------------------
# Helpers
# -------------------
def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)


def save_pickle(obj, path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(obj, f)
    print(f"Saved context embeddings to {path}")


def load_prompt_template(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def build_prompt(template, user_description, target_title, target_description):
    """Fill in the context prompt template."""
    return (template
            .replace("{user_description}", user_description)
            .replace("{target_title}", target_title)
            .replace("{target_description}", target_description))


# -------------------
# LLM pipeline setup
# -------------------
def build_llm_pipeline(model_name: str):
    """Load a HuggingFace text-generation pipeline."""
    print(f"Loading LLM: {model_name} (downloading on first run) ...")
    dtype = torch.float16 if torch.cuda.is_available() else torch.float32
    pipe = hf_pipeline(
        "text-generation",
        model=model_name,
        device_map="auto",
        torch_dtype=dtype,
    )
    print(f"  LLM loaded on: {pipe.device}")
    return pipe


# -------------------
# LLM context generation
# -------------------
def generate_contexts_for_pair(pipe, prompt_text, num_contexts):
    """
    Call the LLM num_contexts times with the same prompt.
    Returns a list of generated context strings.
    """
    messages = [{"role": "user", "content": prompt_text}]
    contexts = []
    for _ in range(num_contexts):
        output = pipe(
            messages,
            max_new_tokens=CONTEXT_MAX_NEW_TOKENS,
            temperature=CONTEXT_TEMPERATURE,
            do_sample=True,
        )
        generated = output[0]["generated_text"]
        if isinstance(generated, list):
            contexts.append(generated[-1]["content"].strip())
        else:
            contexts.append(generated.strip())
    return contexts


# -------------------
# Main
# -------------------
def main(args):
    dataset = args.dataset
    num_contexts = args.num_contexts
    llm_model = args.llm_model
    sbert_model_name = args.sbert_model
    
    # Verify profile_file argument is passed through
    if not hasattr(args, 'profile_file'):
        args.profile_file = None
    if not hasattr(args, 'max_pairs'):
        args.max_pairs = None
    
    # Extract model name from full ID (e.g., "microsoft/phi-3-mini-4k-instruct" → "phi-3-mini-4k-instruct")
    model_name_short = llm_model.split("/")[-1] if "/" in llm_model else llm_model

    data_dir = Path(__file__).resolve().parents[1] / "data" / dataset

    # --- Find user profile file ---
    if args.profile_file:
        # User specified explicit profile file
        profile_path = Path(args.profile_file)
        
        # If it's just a filename (no directory), assume it's in data_dir
        if not profile_path.is_absolute() and "/" not in str(profile_path) and "\\" not in str(profile_path):
            user_text_path = data_dir / profile_path
        else:
            user_text_path = profile_path
        
        if not user_text_path.exists():
            raise FileNotFoundError(
                f"Profile file not found: {user_text_path}\n"
                f"Checked: {user_text_path.resolve()}"
            )
    else:
        # Auto-detect: Look for pattern: *{model_name_short}_N*_T*_text.pkl (handles new filenames with N and T)
        pattern = f"bert_long_term_user_profiles_{model_name_short}_N*_T*_text.pkl"
        profile_files = list(data_dir.glob(pattern))
        
        if not profile_files:
            # Fallback: try old naming without N/T (for backward compatibility)
            old_pattern = f"bert_long_term_user_profiles_{model_name_short}_text.pkl"
            old_file = data_dir / old_pattern
            if old_file.exists():
                user_text_path = old_file
            else:
                raise FileNotFoundError(
                    f"No profile files found matching:\n"
                    f"  {pattern}\n"
                    f"  or {old_pattern}\n"
                    f"Run: python preprocessing/generate_profiles.py --llm_model {llm_model} first"
                )
        else:
            # Use the most recent profile file (sorted by name)
            user_text_path = sorted(profile_files)[-1]

    print(f"Using LLM model: {llm_model}")
    if args.profile_file:
        print(f"Using specified profile file: {user_text_path.name}")
    else:
        print(f"Auto-detected profile file: {user_text_path.name}")
    
    item_meta_path = data_dir / "item_metadata.pkl"
    test_path = data_dir / "test.csv"
    out_path = data_dir / "bert_context_profiles_test.pkl"

    print("Loading raw profile texts and item metadata...")
    user_text_df = load_pickle(str(user_text_path))
    item_meta_df = load_pickle(str(item_meta_path))
    test_df = pd.read_csv(str(test_path))

    # Build lookup dicts
    user_text = {int(row["user_id"]): row["profile_text"]
                 for _, row in user_text_df.iterrows()}
    item_meta = {int(row["item_id"]): {"title": row["title"],
                                        "description_text": row["description_text"]}
                 for _, row in item_meta_df.iterrows()}

    # --- Load prompt template ---
    prompt_template = load_prompt_template(str(PROMPT_PATH))

    # --- Set up LLM pipeline ---
    pipe = build_llm_pipeline(llm_model)

    # --- SBERT encoder ---
    print(f"Loading SBERT model: {sbert_model_name}")
    sbert = SentenceTransformer(sbert_model_name)

    # --- Generate contexts ---
    # Build unique (user_id, item_id) pairs from the test set
    test_pairs = [
        (int(row.user_id), int(row.item_id))
        for row in test_df.itertuples(index=False)
    ]

    context_dict = {}   # {(user_id, item_id): List[np.ndarray shape (384,)]}
    total = len(test_pairs)
    
    # Optionally limit to first N pairs for testing
    if args.max_pairs:
        test_pairs = test_pairs[:args.max_pairs]
        total = len(test_pairs)
    
    print(f"Generating {num_contexts} contexts for {total} test (user, item) pairs...")
    
    # Collect all contexts and metadata for batch SBERT encoding
    all_ctx_texts = []        # List of context strings
    all_ctx_metadata = []      # List of (user_id, item_id, context_idx) tuples
    for idx, (user_id, item_id) in enumerate(test_pairs):
        if user_id not in user_text:
            continue
        if item_id not in item_meta:
            continue

        user_desc = user_text[user_id]
        item_title = item_meta[item_id]["title"]
        item_desc = item_meta[item_id]["description_text"]

        prompt_text = build_prompt(prompt_template, user_desc, item_title, item_desc)

        ctx_texts = generate_contexts_for_pair(pipe, prompt_text, num_contexts)
        
        # Collect contexts and their metadata for batch encoding later
        for ctx_idx, ctx_text in enumerate(ctx_texts):
            all_ctx_texts.append(ctx_text)
            all_ctx_metadata.append((user_id, item_id, ctx_idx))

        if (idx + 1) % 50 == 0 or (idx + 1) == total:
            print(f"  [{idx+1}/{total}] Generated contexts, collected for batch encoding...")
    
    # Batch-encode all contexts at once (much faster than per-pair encoding)
    print(f"\nBatch-encoding {len(all_ctx_texts)} contexts with SBERT...")
    if all_ctx_texts:
        all_ctx_embs = sbert.encode(
            all_ctx_texts,
            batch_size=256,
            convert_to_numpy=True,
            show_progress_bar=True,
        )  # shape (N_contexts, 384)
        
        # Reorganize embeddings back into the context_dict structure
        for (user_id, item_id, ctx_idx), emb in zip(all_ctx_metadata, all_ctx_embs):
            if (user_id, item_id) not in context_dict:
                context_dict[(user_id, item_id)] = []
            context_dict[(user_id, item_id)].append(emb)

    save_pickle(context_dict, str(out_path))
    print(f"Done. Generated contexts for {len(context_dict)} / {total} pairs.")


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Generate GT-aligned LLM contexts for test (user, item) pairs."
    )
    parser.add_argument("--dataset", type=str, default=DEFAULT_DATASET)
    parser.add_argument("--num_contexts", type=int, default=DEFAULT_NUM_CONTEXTS,
                        help="Number of contexts to generate per (user, item) pair.")
    parser.add_argument("--llm_model", type=str, default=DEFAULT_LLM_MODEL,
                        help="HuggingFace model ID, e.g. 'Qwen/Qwen2.5-7B-Instruct'.")
    parser.add_argument("--sbert_model", type=str, default=DEFAULT_SBERT_MODEL,
                        help="Sentence-Transformers model name for encoding contexts.")
    parser.add_argument("--seed", type=int, default=None,
                        help="Seed (for reproducibility notes only; LLM calls are stochastic).")
    parser.add_argument("--profile_file", type=str, default=None,
                        help="Path to profile file (filename or full path). If not specified, auto-detects based on --llm_model.")
    parser.add_argument("--max_pairs", type=int, default=None,
                        help="Limit to first N test pairs (useful for quick testing; default: all).")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_arguments()
    main(args)
